### ISSUE TITLE
Cannot include private methods with apidoc_extra_args

### ISSUE THREAD

**Issue by Dantali0n** [sphinx-contrib/apidoc#14]
When I use `apidoc_extra_args = ['-P']` the private methods starting with **_** are still not included in the generated documentation. The same happens  with --private.

**Comment by stephenfin** [comment]
Can you reproduce this with a direct call to `sphinx-apidoc`? I would assume so, since we're simply passing things through to that executable. If you can, I think you should report this against Sphinx itself. If not, can you please reopen this and provide debug-level logs.

**Comment by Dantali0n** [comment]
@stephenfin Can you provide details on how the logs you expect can be generated as it is not clearly listed in http://www.sphinx-doc.org/en/master/devguide.html

**Comment by stephenfin** [comment]
You'll want to use `-v` when calling `sphinx-build`, which can be specified multiple times. Before that though, can you check if this can be reproduced via a direct call to `sphinx-apidoc`?

I didn't know people couldn't reopen issues. That seems odd, but I can reopen if it turns out that this is an issue.

**Comment by Dantali0n** [comment]
Seems this issue occurs with native `sphinx-apidoc`, do you know how to submit bug reports for this project. It is hard to find the relevant developer documentation for sphinx stuff imo.

**Comment by stephenfin** [comment]
You'll want https://github.com/sphinx-doc/sphinx/issues
